---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-helmrelease
  namespace: flux-system
spec:
  targetNamespace: monitoring
  releaseName: prometheus-for-amp
  interval: 5m
  chart:
    spec:
      chart: prometheus
      version: '15.8.5'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  #
  # Loading the Helm chart values to be overridden from a ConfigMap
  #
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-configmap


