serviceAccounts:
        server:
            create: true
            name: "prometheus-service-account"
            annotations: 
                #
                # Make sure that the Trust policy of this IAM role is configured to trust the target EKS clusters's OIDC provider.
                #
                eks.amazonaws.com/role-arn: arn:aws:iam::937351930975:role/EKS-AMP-ServiceAccount-Role
nodeExporter:
    enabled: true
alertmanager:   
    enabled: false
pushgateway:
    enabled: false
server:
    statefulSet:
        enabled: false
    persistentVolume:   
        enabled: false
    remoteWrite:
#        - url: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-46773539-a8c6-4344-a90b-948381f66811/api/v1/remote_write
        - url: https://aps-workspaces.us-west-2.amazonaws.com/workspaces/ws-f1b785f2-4d12-40ff-b5be-132f8b8ca14b/api/v1/remote_write
          sigv4:
            region: us-east-1
          queue_config:
            max_samples_per_send: 1000
            max_shards: 200
            capacity: 2500
    global:
        scrape_interval: 10s
        scrape_timeout: 10s