---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: awslb-controller-helmrelease
  namespace: flux-system
spec:
  targetNamespace: kube-system
  releaseName: awslb-controller
  interval: 5m
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: '1.4.0'
      sourceRef:
        kind: HelmRepository
        name: eks
        namespace: flux-system
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: awslb-controller-configmap


