---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - awslb-controller-release.yaml
configMapGenerator:
  - name: awslb-controller-configmap
    namespace: kube-system
    files:
      - values.yaml=awslb-controller-values.yaml
configurations:
  - kustomizeconfig.yaml

