---
apiVersion: v2
name: csi-secrets-store-argocd
description: A Helm chart for deploying CSI driver fir Kubernetes Secret Store
type: application
version: 1.0.0
appVersion: "1.0"
dependencies:
- name: csi-secrets-store
  version: 1.0.0
  repository: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
