#
# The Application CRD is the Kubernetes resource object representing a deployed application instance in an environment. 
# It is defined by two key pieces of information:
# 'source' - reference to the desired state in Git (repository, revision, path, environment)
# 'destination' - reference to the target cluster and namespace. 
# When deployed within a cluster, 'destination' is set to 'server' with the URL https://kubernetes.default.svc
#
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3reader
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
  project: sarathy-workloads-project
  source:
    repoURL: git@github.com:vijayansarathy/fluxv2-deployment-apps.git
    targetRevision: HEAD
    path: argo/s3reader
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: nodejs
  syncPolicy:
    automated:
      prune: true    
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m   