apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: crossplane-eks-composition
  annotations:
    argocd.argoproj.io/sync-wave: "1"   
spec:
  ignoreCrossplaneConstraints: false
  package: 937351930975.dkr.ecr.us-west-2.amazonaws.com/crossplane-eks-composition:3.0.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 0
  skipDependencyResolution: false
