---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender-app
  namespace: nodejs
  annotations:
    argocd.argoproj.io/sync-wave: "10"    
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommender-app
      role: backend-service
  template:
    metadata:
      labels:
        app: recommender-app
        role: backend-service
      annotations:
        prometheus.io/scrape: 'true'     
    spec: 
      containers:          
        - name: jvm8  
          image: 937351930975.dkr.ecr.us-east-1.amazonaws.com/k8s-recommender:latest
          imagePullPolicy: Always   
          env:
            - name: POSTGRES_USER
              valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: POSTGRES_PASSWORD
            - name: POSTGRES_DATABASE
              valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: POSTGRES_DATABASE               
            - name: POSTGRES_HOST
              valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: POSTGRES_HOST  
            - name: POSTGRES_PORT
              valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: POSTGRES_PORT                        
            - name: POSTGRES_TABLEPREFIX
              valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: POSTGRES_TABLEPREFIX       
          ports:
            - containerPort: 8080
              name: http 
              protocol: TCP
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m" 
              memory: "1000Mi"
          livenessProbe:
            httpGet: 
              path: /live
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3            
          readinessProbe:
            httpGet: 
              path: /ready
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3        
            
---
apiVersion: v1
kind: Service
metadata:
  name: recommender-svc
  namespace: nodejs
  annotations:
    argocd.argoproj.io/sync-wave: "20"    
spec:
  sessionAffinity: None
  type: ClusterIP  
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: recommender-app
    role: backend-service


---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: post-recommender
  namespace: nodejs
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "30"
spec:
  template:
    spec:
      containers:
        - name: page-down
          image: alpine:latest
          command: ["sleep", "20"]
      restartPolicy: Never