apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "10"  
spec:
  encryptedData:
    credentials: AgCJux/DvhjKxtBiGMGq9DJcO4yZkgAqRJYxDV0Nw8fdsuc53Agk/1SfrGBvhx5BfgZNR3nevEY7mSyeWn3ai6PwKUmKtIHiTUXw4TZALRt9JpidWDsMWGb7ysTt7SxopYrJvzzjxjtZ1pagh7Lo6zC1KluU6d8QjzEEvO2x9jPdCPfvWpn1QPkJbUQekkJXXJTtAxSPa46UmTXDTL2bYamGdtNm/in1qMRXtuhNPtjBHl6cC2ocRaxl19tmHIai5C6kTQR/NrrJFFh51cYzirTUIgVPPua2CUioGBYPn8PbK+QIWhd3exVEighyzZVsSfzn/MCstCpcLg6H6OHzFwHQA1fYGDYR5BtmM+dDWqgqJmYbSPkcxKHw/aJVH1lBjV+29ywrM0i78srj0wPkDmVcmvR9KXommpBllCbIDjmYj7/Zd4+HwD+pcuzj1l3qFN/q/2SicWrXmVy+zWzwnbQSqByWHdsB1eeKn8Bv0IIniDId30RLRm5ekm2NXjGOWg2Y7BZASF2w7ERYrhfLpzUyASmNISvez31yRqdBh6m2XFsKtluhYTLJgMXnjSp4IYVnSCawMtYJdf8I0OoeiTqltTBnsXl/DgnIIUBKyIusjlE18UMAwcQ14ilP60dlrD4mOWXhVm5VHV6X69mFpXZhxEJQNmWdaWfrVHf7acmg19F3PgmmxmXLiArr4p4lX5wjZy8iIlF2bzhGKFWoqG+IPtwtRdC0S6k4KhzMKAPzSMgLDpz/6T+5IT4b/dFeBwp+W5zF4jWfCUaFgBQ8glxWRqfjWL2zW8ksW3wlpi5Ye1kKhk9D6elX6iL5BPupoF8jLetBuz3w4NL19UKeJfXwLaw5Fw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system

