---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealedsecrets 
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"   
spec:
  project: sarathy-workloads-project
  source:
    repoURL: git@github.com:vijayansarathy/fluxv2-deployment-apps.git
    targetRevision: HEAD
    path: deploy/infra-argo/sealed-secrets
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true      
    retry:
      limit: 2
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m
