---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-reader
  namespace: nodejs
  annotations:
    argocd.argoproj.io/sync-wave: "1"  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: s3-reader
      role: web-service
  template:
    metadata:
      labels:
        app: s3-reader
        role: web-service
      annotations:
        prometheus.io/scrape: 'false'     
    spec: 
      dnsConfig:
        options: 
          - name: ndots
            value: "2"
      containers:          
        - name: node  
          image: 937351930975.dkr.ecr.us-west-2.amazonaws.com/k8s-nodeapp:latest
          imagePullPolicy: Always   
          resources:
            requests:
              cpu: "128m"
              memory: "128Mi"
          livenessProbe:
            httpGet: 
              path: /live
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3            
          readinessProbe:
            httpGet: 
              path: /live
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3        
---
apiVersion: v1
kind: Service
metadata:
  name: s3reader-svc
  namespace: nodejs
  annotations:
    argocd.argoproj.io/sync-wave: "2"   
spec:
  sessionAffinity: None
  type: ClusterIP  
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: s3-reader
    role: web-service    

---
apiVersion: batch/v1
kind: Job
metadata:
  name: sleep
  namespace: nodejs
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    spec:
      containers:
        - name: page-down
          image: alpine:latest
          command: ["sleep", "20"]
      restartPolicy: Never