---
apiVersion: v2
name: prometheus
description: A Helm chart for Prometheus
type: application
version: 1.0.0
appVersion: "1.0"
dependencies:
- name: prometheus
  version: 14.1.1
  repository: https://prometheus-community.github.io/helm-charts
