 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::937351930975:role/EKS-SecretsManager-Role
  name: secrets-mounter
  namespace: crossplane-system

#
# Utility Deployment to mount the secrets stored in SSM parameter store and expose them as Kubernetes Secret
# This works in conjunction with a SecretProviderClass resource
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause-app
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pause-app
      role: pause-service
  template:
    metadata:
      labels:
        app: pause-app
        role: pause-service
    spec: 
      serviceAccountName: secrets-mounter
      containers:          
        - name: pause
          image: gcr.io/google_containers/pause-amd64:3.0
          imagePullPolicy: Always   
          env:
            - name: AWS_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: crossplane-aws-provider-credentials
                  key: credentials
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m" 
              memory: "1000Mi"
          volumeMounts:
            - name: crossplane-secrets-store
              mountPath: "/data/aws-credentials"
              readOnly: true    
      volumes:
        - name: crossplane-secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true      
            volumeAttributes:
              secretProviderClass: "crossplane-aws-provider-credentials"        
            

