apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'false'
    spec:
      containers:
      - name: go
        image: 031791575028.dkr.ecr.us-east-1.amazonaws.com/k8s-frontend:v1 # {"$imagepolicy": "flux-system:app-image-stage-policy"}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
