apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgBvvVVaBMZ4xSbPcEfzydwthZdldUDTTlqRec/LS80zdz2iT7TqdUrhaOOI6p+wL7wv/6wax+NRRQOdTokKsHWq8iQZrM16MJkBRePvr6oF9PnzHgcOburEFDWDLYTEl1EDFNICb8jUo0EJgkUibe/t0GE5DCUWn9JPt1QLUa15spTIgcOAoTwLaolofKeKF9mUsrqGAeLzFUcopF8z3WddH2NOn926TTasbeZFs4GGp377AH//bgf1n18BkFOzWWSv+jV5am2cc8A/E17QQuJaJOQZG8aDfcu9FlZKuHWEgjfyDASEvzJtqyB984HhzIolRG2a3F2AgqPwBCOMn+zSlnHg2Ao6J/48c//w46/kvX+D8l4o2cXhgnSKBZ/AcEvu5LgojW2oXZxWrXrdzvfenDU1grbHgdeW+GdXZt54wzisSzKBHQrONedmo9gkmU20plRCeto0nngArc7Y85eIreptMd5TvnpaH1QpHyVq8hQ214xnLLcN16ZCuSb/OvHfr/qGgTjDkWn5JbrYMEVe4paxfosKbEO8VTOkE353NV985nXfI9VPHmrrftTnCK/cdrRI8k4kRsXuOVnQzscZXIitowubjqK5FlZql3xT/Us9UJuqNfVFkro1kSCgxSNJK3jUARY0AGLTvuMt9UsRGyjBO4VcmUQMSC3DKgv9gJH2lVF5d4brOouUBLZy87Gb7GvBuNC1nfGiH2Xjh4Eo59/lTIn/nknAgi6lmbKHjGDeExyrjlXzu9rB9yyvPsXHa97lmhmzyanF38xKXM1EVqpH3bikTwTa0EgjXnHrXbEnhDo2ivK2D+VV4EMKH3ClkDiOZgCjlR+XFMJemenKCZzdxw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system
    type: Opaque

