apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgCPlmQKDOoeLrjLYDkD7juYbKQkTdQztF7I6qq3aM+rLuSLu+VSJA4l7A+uihYISM8Nsc+D5wxHRJO3QiSjR/RfwmmHi6MhspxxTyzCFWEH45L+DkGDT0FFfqb8TWnzFGDq3IHAldWLNMjxAlQbmubz+CLiCzoykrdfpzS5Yur+c1nMS5kekfLTKPr2tD52VUIk6SYB0MlZN1q/sABeBPQh8VTN4z+Lll2EFxN1WzNEIK6st04N2S3fiy9R1QdNGb438q3+uOO/gRS5YyiuizchViltevYAwHNsyoR+HHJHbpMBTYkiSBKA8bLvaVdvhJ8bx+Ic9WzWgdwugBFsyQF5B7ae2zAhc7fOXHGCjLPZ7JVpmZa/c2MJAaonhPR41pk4MePGaZbR0ga5wLl3v3KsTHveBrNZ1QPHMk3iBlQTAePA4SofqtWvuYXO9twD4CHsJ9xwGUMX5oDObuwjCWaA5XjWkrkl9qKrdfUhmR3w6qvD6j+bhfS3DY4AHdcrefhKdW8boykZlYCDs9qDmXZsUMVPqOANa1hhBFiAw/9a6X8Q9Re6vGkze0rqq7ZCkrOCJAhHVQU8my3nmq5V0SN10Qk9eKF/X7Ia2MGsJYVX1jncmi9scXAVfMDSjmuyS0NAMCZAvoTVRCAu7wyI8wxCpRiYXiOJnWsARMIiarn6NITCjkU9Zs/oUt4Tc/baU26//4M8HDgKjT4MJpB9UVuNrtIY4uLo4hTfU5uOZWJukrOp/5pVY7cIXXs48+z8/iTSG/BJCSW8MWguBXHtJiBKxkKAqUzuLp5NbhQZfP71S94PFb8n/7yrZd0zWqje2CA1SvZ8PJ5IT0r2WTDZ7ekx0MK2fQ==
  template:
    metadata:
      name: aws-credentials
      namespace: crossplane-system

