---
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-secret-mount
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "4"      
spec:
  template:
    spec:
      containers:
        - name: sleep
          image: alpine:latest
          command: ["sleep", "30"]
      restartPolicy: Never
  backoffLimit: 0