---
apiVersion: eks.sarathy.io/v1beta1
kind: EKSCluster
metadata:
  name: eks-prod-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "300"   
spec:
  parameters:
    region: us-west-2
    version: "1.20"
    workload: "non-gpu"
    size: 2
  compositionRef:
    name: amazon-eks-cluster
  writeConnectionSecretToRef:
    namespace: eks
    name: eks-prod-cluster-connection