apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - namespace.yaml
  - ingress.yaml
  - ../../../base/frontend

transformers:
- labels.yaml

patches:
- path: deployment-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment