---
apiVersion: v1
kind: Namespace
metadata:
  name: nodejs

---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-reader
  namespace: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: s3-reader
      role: web-service
  template:
    metadata:
      labels:
        app: s3-reader
        role: web-service
      annotations:
        prometheus.io/scrape: 'false'     
    spec: 
      dnsConfig:
        options: 
          - name: "ndots"
            value: 2    
      containers:          
        - name: node  
          image: 937351930975.dkr.ecr.us-west-2.amazonaws.com/k8s-nodeapp:latest
          imagePullPolicy: Always   
          resources:
            requests:
              cpu: "128m"
              memory: "128Mi"
          livenessProbe:
            httpGet: 
              path: /live
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3            
          readinessProbe:
            httpGet: 
              path: /live
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3        
---
apiVersion: v1
kind: Service
metadata:
  name: s3reader-svc
  namespace: nodejs
spec:
  sessionAffinity: None
  type: ClusterIP  
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: s3-reader
    role: web-service    

